### ISSUE TITLE
transitionend event

### ISSUE THREAD

**Issue by Snowshield** [mkay581/wait-for-element-css#1]
Why "transitionend" event is not used? It supports all browsers ie10+

**Comment by mkay581** [comment]
@Snowshield, I apologize for such of a delay in getting back with you.

Listening to the `transitionend` on an Element will allow you to wait until an Element's transition has ended, but this approach is limited. The event doesn't fire when:

1. An element's display is manipulated before the event has a chance to fire (i.e. `display` is set to `none` or if the css transition property is removed)
1. There are no css transition properties specified, which doesn't allow us to run the same animation-completion logic on elements which may or may not be animated.

Help this helps!
